### ISSUE TITLE
Console output during zsh initialization detected

### ISSUE THREAD

**Issue by willdebernardi** [romkatv/powerlevel10k#2152]
I am facing an issue with my install of p10k. With instant prompt turned on, every time I load up the terminal, I get the following message:

> [WARNING]: Console output during zsh initialization detected.
> 
> When using Powerlevel10k with instant prompt, console output during zsh
> initialization may indicate issues.
> 
> You can:
> 
>   - Recommended: Change ~/.zshrc so that it does not perform console I/O
>     after the instant prompt preamble. See the link below for details.
> 
>     * You will not see this error message again.
>     * Zsh will start quickly and prompt will update smoothly.
> 
>   - Suppress this warning either by running p10k configure or by manually
>     defining the following parameter:
> 
>       typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
> 
>     * You will not see this error message again.
>     * Zsh will start quickly but prompt will jump down after initialization.
> 
>   - Disable instant prompt either by running p10k configure or by manually
>     defining the following parameter:
> 
>       typeset -g POWERLEVEL9K_INSTANT_PROMPT=off
> 
>     * You will not see this error message again.
>     * Zsh will start slowly.
> 
>   - Do nothing.
> 
>     * You will see this error message every time you start zsh.
>     * Zsh will start quickly but prompt will jump down after initialization.
> 
> For details, see:
> https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt
> 
> -- console output produced during zsh initialization follows --

This is the end of the output, there is nothing produced below, as the error would sugges.t

I have looked into this issue thoroughly on both the Github repo and other places, and it appears to have been pretty common, but I have not managed to find a solution which works for me. Apparently this issue was fixed at some point in the last couple of years, but I am having it again. I have done the obvious things, like fully updated both p10k and oh-my-zsh., uninstall and reinstalled both of them, modified my .zshrc (which I have included below), etc... Assistance would be greatly appreciated.

.zshrc:

> if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
>   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
> fi
> 
> export ZSH=$HOME/.oh-my-zsh
> 
> ZSH_THEME="powerlevel10k/powerlevel10k"
> 
> plugins=(git)
> 
> source $ZSH/oh-my-zsh.sh
> 
> [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

**Comment by romkatv** [comment]
I've never seen this problem before. I don't have any ideas what might be causing it.

**Comment by romkatv** [comment]
I've just reproduced it. My current guess is that an update to oh-my-zsh had this side effect. I'll update here once I debug further.

**Comment by romkatv** [comment]
A bug was introduced to Oh My Zsh here: https://github.com/ohmyzsh/ohmyzsh/commit/3dd83a22a160249a71631a51490fd3b89d1b3975.

I've added a workaround. Please update powerlevel10k and try again.

**Comment by willdebernardi** [comment]
> A bug was introduced to Oh My Zsh here: [ohmyzsh/ohmyzsh@3dd83a2](https://github.com/ohmyzsh/ohmyzsh/commit/3dd83a22a160249a71631a51490fd3b89d1b3975).
> 
> I've added a workaround. Please update powerlevel10k and try again.

Issue fixed! Thank you very much for your super quick turnaround on this.

**Comment by romkatv** [comment]
Thanks for reporting and testing my changes.

**Comment by romkatv** [comment]
I've reported the bug upstream here: https://github.com/ohmyzsh/ohmyzsh/issues/11314#issuecomment-1379492472

**Comment by p-linnane** [comment]
Hello. I am experiencing this when using the Homebrew tap. Is it possible to cut a new release and update the formula?

**Comment by romkatv** [comment]
The bug in Oh My Zsh has been fixed: https://github.com/ohmyzsh/ohmyzsh/commit/17ea97332b2f2285e3c2e1a00f6745fb1fe1cec5. Update Oh My Zsh and the warning will go away.

**Comment by Xmuluneh** [comment]
how can I fix this issue please help me 
zsh: locking failed for /Users/muluneh/.zsh_history

**Comment by Emiltonn** [comment]
I solved this, deleting the ~/.histfile

So
`sudo rm -f ~/.histfile`

**Comment by JaswantBhartiya** [comment]
I got the same error and when I reconfigure .zshrc file, It does not show this massage anymore. In my case, the problem is in the plugin syntax.

Before : 
```
plugin=
(
    git
    zsh-autosuggestions
)
```

This is how it was solved:
`plugin=(git zsh-autosuggestions)`

**Comment by shadan-arif** [comment]
> A bug was introduced to Oh My Zsh here: [ohmyzsh/ohmyzsh@3dd83a2](https://github.com/ohmyzsh/ohmyzsh/commit/3dd83a22a160249a71631a51490fd3b89d1b3975).
> 
> I've added a workaround. Please update powerlevel10k and try again.

The last few Lines of the error that is being shown to be goes like:
-- console output produced during zsh initialization follows --
iconv: iconv_open, -t): Invalid argument
Error converting string from to UTF-8

I'm being shown this error every time I execute any command like pwd, ls, etc. Do you have any other way around this? I have tried turning off the instant prompt, but the issue still persists.

**Comment by romkatv** [comment]
@shadan-arif You could try to Google the error message. Here's one of the first links: https://gitlab.com/gnachman/iterm2/-/issues/11543. I haven't tried it myself.

**Comment by shadan-arif** [comment]
> @shadan-arif You could try to Google the error message. Here's one of the first links: https://gitlab.com/gnachman/iterm2/-/issues/11543. I haven't tried it myself.

Thanks a lot for your reply; I found a solution down a few links in the article.

Note the below code didn't work for me:
`echo 'export LANG=en_US.UTF-8' >> ~/.zshrc`

Rather, navigate inside the **Environment** (Settings - Profile - Terminal - iterm2), change LANG to something with UTF-8 eliminated the issue.
<img width="956" alt="Screenshot 2024-06-09 at 2 51 26 PM" src="https://github.com/romkatv/powerlevel10k/assets/67832174/3b5d1b58-6f85-4322-ae4d-cb794c162f17">

**Comment by MohamedHNoor** [comment]
Thank you, @shadan-arif! Your method worked for me.

**Comment by kaustavb7** [comment]
Thanks @shadan-arif , It worked.

**Comment by janachinna** [comment]
In my case there was a plugin sourced but it was an uninstalled one. So i had to manually remove that entry from ~/.zshrc and after that this error stopped.

**Comment by AnmolTomer** [comment]
thanks a ton @shadan-arif 
this worked for me as well https://github.com/romkatv/powerlevel10k/issues/2152#issuecomment-2156414128

**Comment by dabchinsky** [comment]
I fixed it by commenting the line "source ~/powerlevel10k/powerlevel10k.zsh-theme" in .zshrc, restarted zsh, uncommented this line and restarted zsh again.

**Comment by DiveAnt** [comment]
i tried commenting the source ~/powerlevel like @dabchinsky said..but it just went show up again when i open up another window.. so i tried commenting out the if command in the top of the .zshrc file.. 

```
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
#if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  #source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
#fi
```
