### ISSUE TITLE
Cursor position incorrect when using Laravel 10 with prompt element 

### ISSUE THREAD

**Issue by jamesdeacon** [romkatv/powerlevel10k#2534]
When the Laravel prompt element is turned on and Laravel 10 is installed, the cursor shows up in the incorrect position, see screenshot for more detail. On top of this the Laravel version number is also showing in the incorrect color, it should be showing in red as it does for all other Laravel versions.

<img width="489" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/1061824/c75e0dc1-c1c2-4ae3-8719-1f9611d0622a">

**Comment by romkatv** [comment]
What terminal is this and what is the output of `locale`?

**Comment by jamesdeacon** [comment]
Screenshot is from iTerm but I see the same behaviour on MacOS Terminal.

Output of locale is:

```
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
```

**Comment by romkatv** [comment]
Does the output of the following command contain colored bits? Could you post a screenshot?

```zsh
php artisan --version
```

This needs to be run in the project directory.

**Comment by romkatv** [comment]
Wow. They'll probably fix this so that colors aren't written when stdout is not a TTY, but in the meantime I can add a workaround.

Please send me the output of the following command. Hopefully it'll be the last one I'll ask you to run.

```zsh
printf '%q\n' "$(php artisan --version)"
```

**Comment by jamesdeacon** [comment]
Sure thing, here's that output:

<img width="1039" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/1061824/f016fd57-61f5-45c7-a5ea-f2e1f368b690">

Just for reference, `php artisan --version` outputs the color on projects that are on Laravel 9 too but the cursor is in the correct position and the color on the prompt element is correct too

<img width="1121" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/1061824/34f9b080-8ebc-4ea3-965c-cdd92ab5a8cf">

**Comment by romkatv** [comment]
Fixed. Please update powerlevel10k and verify whether it now works correctly for you.

> Just for reference, `php artisan --version` outputs the color on projects that are on Laravel 9 too but the cursor is in the correct position and the color on the prompt element is correct too

Apparently, versions prior to 10 don't have this bug: they output colors only when the stdout is a TTY. You can verify this with `php artisan --version | cat`. The output should not have colors but with 10.40.0 it does.

**Comment by jamesdeacon** [comment]
You probably already know this but just thought I'd add, when it's Laravel 9 the output of that command is much cleaner:

<img width="1121" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/1061824/f07fdf63-7727-497a-b656-64af6f3271d8">

A lot of this is over my head so apologies if it's irrelevant information!

**Comment by jamesdeacon** [comment]
I've installed powerlevel10k using brew. What's the best way for me to update seeing as brew is showing as up-to-date

**Comment by romkatv** [comment]
You could ditch brew for now and use the manual installation option, at least until I cut a new release.

1. Comment out this line in `~/.zshrc`:
   ```zsh
   source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme
   ```
2. Run this:
   ```zsh
   git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
   echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc
   ```
3. Restart zsh with `exec zsh`.

**Comment by jamesdeacon** [comment]
I've done that and it's not showing a Laravel version at all anymore:

<img width="1121" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/1061824/591e6e48-9394-48ec-8cc5-207670a54b5a">

This is also the case on any Laravel projects, not just Laravel 10.

I still have the `laravel_version` set in my `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS`

<img width="1172" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/1061824/45d0a719-3e96-4e2a-9367-fcc7798f08d0">

**Comment by jamesdeacon** [comment]
Hooray! All working

<img width="1131" alt="image" src="https://github.com/romkatv/powerlevel10k/assets/1061824/3756b737-93da-4ca1-a167-61d49442f460">

Thanks so much

**Comment by romkatv** [comment]
Thanks a ton for you help on this issue: from reporting and remote debugging to verifying and even catching the silly bug I pushed! <3
