### ISSUE TITLE
Incorrect git status when .git dir is a reference

### ISSUE THREAD

**Issue by infokiller** [romkatv/powerlevel10k#491]
Hey!

I recently moved the `.git` directory in my `$HOME` (used for tracking my config files) to a different location (`~/.local/var/git_dirs/config`). 
I later added a symlink from `~/.git` to this new git directory to be able to use git commands from my home dir without setting `--git-dir` or `$GIT_DIR`, but that causes the git status shown by p10k to be incorrect. For example, right now I have no changes in my git repo:
```sh
❯ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

However, this is what the prompt looks like:
![image](https://user-images.githubusercontent.com/10516814/74426344-dc1c7900-4e5d-11ea-9441-32f94036a55c.png)
The same thing happens if I delete `~/.git` but use `export GIT_DIR=~/.local/var/git_dirs/config`.

Any advice how I should debug this?

Please let me know if you prefer I open an issue in the gitstatus repo.

Thanks!

**Comment by romkatv** [comment]
Thanks for the report. I've fixed this bug in the source code but haven't yet rebuilt gitstatusd binaries.

What OS are you using? This bug is not a regression and is unlikely to affect many users, so I'll make an emergency gitstatusd release only for the OS you care about. The rest will be rebuilt in due course.

**Comment by infokiller** [comment]
Thanks for the quick fix! I'm using Arch Linux.

I tried to test the fix by building gitstatus from source using:

```sh
zsh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/gitstatus/master/build.zsh)"
```

Then I copied the binary built in `/tmp/gitstatus/gitstatus/bin/gitstatusd-linux-x86_64` to `powerlevel10k/gitstatus/bin/gitstatusd-linux-x86_64`. When I open a new shell, it seems the issue is not fixed.
Did I do anything wrong?

**Comment by romkatv** [comment]
Let's try with a simpler test case. Please run the following command:

```zsh
() {
  emulate -L zsh -o err_return
  local d=/tmp/gitstatus-test
  mkdir $d
  mkdir $d/foo
  mkdir $d/bar
  git -C $d/foo init
  touch $d/foo/x
  git -C $d/foo add x
  git -C $d/foo commit -m first
  ln -s $d/foo/.git $d/bar/.git
  cd $d/bar
}
```

What does prompt say?

If you are using an older binary without the fix, it should say the repository is clean. The newer binary with my fix should say there is one unstaged change (file `x` has been deleted).

**Comment by infokiller** [comment]
Seems like the new binary is being used:

![image](https://user-images.githubusercontent.com/10516814/74538389-cdf55800-4f44-11ea-9e49-358c7b3c034d.png)

I think I know where the issue is - my `~/.git` is actually not a symlink, but a file with this content (this was set by git somehow) `gitdir: /home/username/.local/var/git_dirs/config`. I just tested with `~/.git` being a symlink and indeed it works now. Using `$GIT_DIR` also doesn't work for me.
For my specific use case I can just make `~/.git` a symlink.

**Comment by romkatv** [comment]
> my `~/.git` is actually not a symlink, but a file with this content (this was set by git somehow) `gitdir: /home/username/.local/var/git_dirs/config`. I just tested with `~/.git` being a symlink and indeed it works now. Using `$GIT_DIR` also doesn't work for me.

I reproduced both of these. Will fix when I get another chunk of free time.

**Comment by infokiller** [comment]
Many thanks! 
And please keep doing these great projects, anything you make is pure gold!

**Comment by romkatv** [comment]
Thanks :hugs:

**Comment by romkatv** [comment]
I've fixed this somewhat although there are still several differences compared to `git`.

- Bare repositories are not supported.
- All `GIT_*` environment variables are ignored except `GIT_DIR`. This includes `GIT_WORK_TREE`.
- If `GIT_DIR` is set but `core.worktree` isn't, `dirname $GIT_DIR` is used as `worktree`. If the last component of `GIT_DIR` is a symbolic link, it's not resolved. (`git` would use the current directory as `workdir` in this case.)
- You cannot open the same repo multiple times with different values of `worktree` in the same zsh session.
- Repositories get discovered from under their `.git` directories.

I think this is good enough for now.

When storing a Git repository someplace other than `worktree/.git/`, set `core.worktree` in the repository's config. This will avoid pitfalls gitstatus pitfalls and make it harder to shoot yourself in the foot.

**Comment by infokiller** [comment]
Great, will do, thanks a lot!

**Comment by romkatv** [comment]
Please rebuild gitstatusd and give it a try.

- It should work when `~/.git` is a file.
- It should work when you set `GIT_DIR` provided that either:
  - `GIT_DIR` points to a file or directory stored in your home directory. The target can be a symbolic link.
  - The repository's config contains `core.worktree` pointing to your home directory.

**Comment by infokiller** [comment]
Both work now, many thanks!

**Comment by romkatv** [comment]
Thanks for the confirmation. I've pushed a fresh `gitstatusd-linux-x86_64` binary. You can `git pull` it.
